---
- name: Determine mount unit name
  set_fact:
    glfs_unit: "{{ glfs_mount_point[1:] | replace('/', '-') }}.mount"

- name: Install GlusterFS server package
  package:
    name: "{{ glfs_package[ansible_os_family] }}"

- name: Create brick directory
  file:
    path: "{{ glfs_brick_root }}/{{ glfs_volume }}"
    state: directory
  tags:
    - glusterfs

- name: Create GlusterFS volume
  gluster_volume:
    state: present
    name: "{{ glfs_volume }}"
    cluster: "{{ glfs_hosts | default(ansible_play_batch) }}"
    bricks: "{{ glfs_brick_root }}/{{ glfs_volume }}"
    replicas: "{{ (glfs_hosts | default(ansible_play_batch)) | length }}"
  run_once: true
  tags:
    - glusterfs
